import { fixupPluginRules } from "@eslint/compat";
import _import from "eslint-plugin-import";
import prettier from "eslint-plugin-prettier";
import react from "eslint-plugin-react";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        extends: [tseslint.configs.recommended],
        ignores: ["**/autogenerated-types/**", "**/dist"],
        plugins: {
            react,
            prettier,
            "simple-import-sort": simpleImportSort,
            import: fixupPluginRules(_import),
        },

        languageOptions: {
            globals: {},
        },

        rules: {
            "prettier/prettier": "error",
            "@typescript-eslint/ban-ts-comment": "warn",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
            "@typescript-eslint/no-this-alias": "warn",
            "@typescript-eslint/no-unsafe-function-type": "warn",
            "@typescript-eslint/no-unused-expressions": [
                "error",
                {
                    allowShortCircuit: true,
                    allowTernary: true,
                    allowTaggedTemplates: true,
                },
            ],
            "@typescript-eslint/no-unused-vars": [
                "error",
                { argsIgnorePattern: "^_", caughtErrors: "none", ignoreRestSiblings: true },
            ],
            "simple-import-sort/imports": "error",
            "simple-import-sort/exports": "error",
            "import/first": "error",
            "import/newline-after-import": "error",
            "import/no-duplicates": "error",
            eqeqeq: "error",
            "jsx-a11y/anchor-is-valid": "off",
            "jsx-a11y/anchor-has-content": "off",
            "prefer-rest-params": "off",
            "react-hooks/exhaustive-deps": "off",
            "react/style-prop-object": "off",
            "prefer-ts-expect-error": "off",
        },
    },
    {
        files: ["**/*.stories.tsx"],

        rules: {
            "import/no-anonymous-default-export": "off",
        },
    },
);
